workspace:
  base: /go
  path: src/github.com/cdreier/Impact

pipeline:

  pack:
    image: node
    commands:
      - npm install
      - npm run buildwm

  build:
    image: drailing/go_packr_zip
    commands:
      - cd weltmeister/api
      - go get
      - GOOS=linux GOARCH=amd64 packr2 build -v -o ${DRONE_REPO_NAME}-${DRONE_TAG}-linux-amd64
      - GOOS=darwin GOARCH=amd64 packr2 build -v -o ${DRONE_REPO_NAME}-${DRONE_TAG}-darwin-amd64
      - GOOS=windows GOARCH=amd64 packr2 build -v -o ${DRONE_REPO_NAME}-${DRONE_TAG}-win-amd64.exe
      - mkdir release
      - zip release/${DRONE_REPO_NAME}-${DRONE_TAG}-linux-amd64.zip ${DRONE_REPO_NAME}-${DRONE_TAG}-linux-amd64
      - zip release/${DRONE_REPO_NAME}-${DRONE_TAG}-darwin-amd64.zip ${DRONE_REPO_NAME}-${DRONE_TAG}-darwin-amd64
      - zip release/${DRONE_REPO_NAME}-${DRONE_TAG}-win-amd64.zip ${DRONE_REPO_NAME}-${DRONE_TAG}-win-amd64.exe

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: weltmeister/api/release/*
    when:
      event: tag